#----------------------------------------------
# DO NOT TOUCH TEHSE UNLESS YOU KNOW WHAT YOU'RE DOING!
debug: false
version: 2.23.0.4
#----------------------------------------------

# You can edit from here:

player-shop:
  # Allow teleporting to player shops
  teleport:
    enabled: true
    # Warmup in seconds. Set to 0 to disable.
    warmup: 5
    allow-movement: false

admin-shop:
  # Allow teleporting to admin shops
  teleport:
    enabled: true
    # Warmup in seconds. Set to 0 to disable.
    warmup: 5
    # Allow the player to move during countdown
    allow-movement: false
  # Allow remote open admin shops
  remote: false

# How often should the shops refresh? (in seconds) keep it above 30 seconds to avoid lag.
refresh-rate: 60

economy:
    # Set the price limit for trades
    selling-price-limit: 100000000.00
    # Currency Item:
    sell-item:
      # Name format. Use %price% for the price.
      name: "Price: §f$%price%"
      material: GOLD_NUGGET
      glow: true
      lore:
        - "§bClick to edit"
    # Currency Item:
    buy-item:
      # Name format. Use %price% for the price.
      name: "You get: §f$%price%"
      material: GOLD_NUGGET
      glow: true
      lore:
        - "§bClick to edit"


# Messages: use & or §  for color codes.
messages:
  prefix: "§8[§bShopkeepersAddon§8] §r"
  no-permission: "§cYou don't have permission to do that!"
  close-inventory-button: "§c§l✖"
  previous-page-button: "§b§lPrevious Page"
  next-page-button: "§b§lNext Page"
  admin-teleport-title: "§cTeleporting...\n§fto Admin Shop"
  player-teleport-title: "§cTeleporting...\n§fto Player Shop"
  teleport-cancelled: "§cYou moved! Teleportation cancelled!"
  teleport-warmup: "§cTeleporting in §f{time}§c seconds..."
  teleport-success: "§aTeleported to shop!"
  teleport-title: "§cTeleporting..."
  teleport-subtitle: "§fin §f%time%§f seconds..."
  no-money: "§cYou don't have enough money!"
  no-money-owner: "§cThe shop owner does not have enough money to make this transaction!"
  set-price: "§aEnter the price for this item in chat."
  price-change-cancelled: "§cPrice change cancelled!"
  price-changed: "§aPrice changed to §f%price%§a."
  invalid-price: "§cInvalid price! Please enter a valid number."
  shop-set: "§aShop set successfully! Teleport to your shop using §f/visitShop"
  no-shop: "§cThis player has not setup a shop using §f/setshop §ccommand."
  no-shop-lore:
    - "&cThis player has not setup a shop."
    - "&cUse &f/setshop &c to setup."


  shops:
    shops-ui: "§8§lShops"
    player-shops-ui: "§8§lPlayer Shops"
    player-items-ui: "§8§lPlayer Items"
    admin-shops-ui: "§8§lAdmin Shops"
    admin-items-ui: "§8§lAdmin Items"
    players-list-ui: "§8§lPlayers"
    admin-sellers-ui: "§8§lAdmin Sellers"
    player-sellers-ui: "§8§lPlayer Sellers"

