name: ShopkeepersNavAddon
version: '1.0'
description: i dont know what to put here
authors: [MrFlyn]
depend:
  - Shopkeepers
softdepend:
  - PlotSquared
main: dev.MrFlyn.shopkeeperNavAddon.Main
api-version: '1.14'

commands:
  shops:
    description: shop
    usage: '/<command>'

permissions:
  # Command permissions:
  SNA.command.shops:
    description: shops
    default: op
