name: ShopkeepersNavAddon
version: '1.2'
description: i dont know what to put here
authors: [MrFlyn]
depend:
  - Shopkeepers
softdepend:
  - PlotSquared
main: dev.MrFlyn.shopkeeperNavAddon.Main
api-version: '1.14'

commands:
  shops:
    description: shop
    usage: '/<command>'
  sna:
    description: parent command
    usage: '/<command> []'

permissions:
  SNA.command.shops:
    description: shops
    default: op
  SNA.teleport:
    description: teleport on click
    default: op
  SNA.command.help:
    description: show help message.
    default: op
  SNA.admin:
    description: allows reload command.
    default: op